apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: s3-bucket-composition
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: crossplane-composition-project
  source:
    chart: argo-testing
    repoURL: https://Yaswanth45.github.io/helm-charts
    targetRevision: 0.2.2
    helm:
      releaseName: argo-testing
  destination:
    server: https://kubernetes.default.svc
    namespace: runtime-demo
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 60s
        factor: 2
        maxDuration: 1m
